Algoritmo "FuncoesAritmeticas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/12/2025
Var
// Seção de Declarações das variáveis 
   A: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      A <- Int(RaizQ(982374))
      Escreva(A)
Fimalgoritmo